# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Lint & Unit test

"on":
  workflow_call:
    inputs:
      gems:
        required: false
        type: string
        default: ""

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Install Gems
        run: chef gem install -N "${{ inputs.gems }}"
        if: ${{ github.event.inputs.gems != '' }}
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Run RSpec
        run: chef exec rspec -f j -o tmp/rspec_results.json -f p
        env:
          CHEF_LICENSE: accept-no-persist
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          json-path: tmp/rspec_results.json
        if: always()

  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@2.0.4
      - name: Run Cookstyle
        run: chef exec cookstyle --display-cop-names --extra-details
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run yaml Lint
        uses: actionshub/yamllint@v1.1.1

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@v2.1.0
