# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: hashicorp-aws CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  cancel-previous:
    name: Cancel Previous Runs In Order to Allocate Action Resources Immediately for Current Run
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.10.1
        if: ${{github.ref != 'refs/head/master'}}
        with:
          access_token: ${{ github.token }}

  code-styles:
    uses: ./.github/workflows/yml-and-md-style-checks.yml

  docker-image:
    name: Publish docker images for "AMI Build Test"
    needs: code-styles
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        docker: [
          {dockerfile-path: tests/machine-learning, image-name: hashicorp-aws-machine-learning-test},
          {dockerfile-path: tests/react, image-name: hashicorp-aws-react-test},
          {dockerfile-path: tests/kong, image-name: hashicorp-aws-kong-test},
          {dockerfile-path: tests/webservice, image-name: hashicorp-aws-webservice-test},
          {dockerfile-path: tests/elk, image-name: hashicorp-aws-elk-test}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jack20191124
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker.dockerfile-path }}
          push: true
          tags: jack20191124/${{ matrix.docker.image-name }}:latest

  tests:
    name: AMI Build Test
    needs: docker-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-directory: [
          tests/machine-learning/images,
#          tests/react/images,
#          tests/kong/images,
          tests/webservice/images,
          tests/elk/images,
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker for AMI Tests
        uses: docker-practice/actions-setup-docker@master
      - run: |
          cd ${{ matrix.test-directory }}
          ./run-tests.sh

  documentation-ci-cd:
    name: Test Documentation Build & Deploy Documentation to GitHub Pages
    needs: [tests]
    outputs:
      outcome: ${{ job.status }}
    continue-on-error: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: QubitPi
          user_email: jack20220723@gmail.com

  slack-notification:
    name: Send Slack Notification
    if: ${{ always() }}
    needs: documentation-ci-cd
    uses: QubitPi/hashicorp-aws/.github/workflows/slack-notification.yml@master
    with:
      job-status: ${{ needs.documentation-ci-cd.outputs.outcome }}
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
