# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: hashicorp-aws CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  code-styles:
    uses: ./.github/workflows/yml-and-md-style-checks.yml

  docker-image:
    name: Publish docker images for "AMI Build Test"
    needs: code-styles
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        docker: [
          {dockerfile-path: tests/machine-learning, image-name: hashicorp-aws-machine-learning-test},
          {dockerfile-path: tests/kong, image-name: hashicorp-aws-kong-test},
          {dockerfile-path: tests/react, image-name: hashicorp-aws-react-test},
          {dockerfile-path: tests/webservice, image-name: hashicorp-aws-webservice-test}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jack20191124
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker.dockerfile-path }}
          push: true
          tags: jack20191124/${{ matrix.docker.image-name }}:latest

  tests:
    name: AMI Build Test
    needs: docker-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-directory: [
          tests/machine-learning/images,
          tests/kong/images,
          tests/react/images,
          tests/webservice/images
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker for AMI Tests
        uses: docker-practice/actions-setup-docker@master
      - run: |
          cd ${{ matrix.test-directory }}
          ./run-tests.sh
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  list-auxiliary-scripts:
    name: Listing Scripts to Test for "Test auxiliary/scripts"
    needs: code-styles
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-auxiliary-scripts.outputs.paths }}
    steps:
      - name: List Files
        id: list-auxiliary-scripts
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "auxiliary/scripts"
          ext: ".sh"

  test-scripts:
    name: Test auxiliary/scripts
    needs: list-auxiliary-scripts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: ${{ fromJson(needs.list-auxiliary-scripts.outputs.paths) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ${{ matrix.test-suite.desc }}
        run: docker run --rm -v $(pwd)/${{ matrix.script }}:/test/script.sh ubuntu /test/script.sh

  documentation-ci-cd:
    name: Test Documentation Build & Deploy Documentation to GitHub Pages
    needs: [tests, test-scripts]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: QubitPi
          user_email: jack20220723@gmail.com
